# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


# we use the secp256k1 implementation:
[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=v1.8.21"

   # Prevent dep from pruning build scripts and codegen templates
   # note: this leaves the whole go-ethereum package in vendor
   # can be removed when https://github.com/golang/dep/issues/1847 is resolved
   [[prune.project]]
     name = "github.com/ethereum/go-ethereum"
     unused-packages = false

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=0.31.5"

[[override]]
  name = "github.com/btcsuite/btcutil"
  revision = "ab6388e0c60ae4834a1f57511e20c17b5f78be4b"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "=v0.12.1"

[[override]]
  name = "github.com/golang/protobuf"
  version = "~1.1.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "~0.14.1"

[[constraint]]
  name = "github.com/btcsuite/btcd"
  revision = "ed77733ec07dfc8a513741138419b8d9d3de9d2d"

[[override]]
  name = "github.com/go-interpreter/wagon"
  source = "github.com/perlin-network/wagon"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
