version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bluele/hypermint
    docker:
      - image: golang:1.12.4-stretch
    steps:
      - checkout
      - run:
          name: "resolve dependencies"
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure -v -vendor-only=true
      - run:
          name: "build"
          command: |
            make build
      - run:
          name: "test"
          command: |
            make test

  contract-test:
    working_directory: /go/src/github.com/bluele/hypermint
    docker:
      - image: rust:1.34.1-stretch
    steps:
      - checkout
      - run:
          name: "test"
          command: |
            cd hmc && cargo test

  e2e-test:
    working_directory: /go/src/github.com/bluele/hypermint
    docker:
      - image: bluele/go-rust:0.1.0
    steps:
      - checkout
      - run:
          name: "resolve dependencies"
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure -v -vendor-only=true
      - run:
          name: "test"
          command: |
            make e2e-test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - contract-test:
          filters:
            tags:
              only: /.*/
      - e2e-test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
