apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypermint
  labels:
    app: hypermint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypermint
  template:
    metadata:
      name: hypermint
      labels:
        app: hypermint
    spec:
      containers:
      - name: hypermint
        image: bluele/hypermint:0.1.0
        ports:
        - containerPort: 26657
