[package]
name = "hmcdk_codegen"
version = "0.1.0"
authors = ["Jun Kimura <junkxdev@gmail.com>"]
edition = "2018"

[dependencies]
abi = { path = "../abi" }
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"

[lib]
proc-macro = true
